services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27018:27017"  # Changed external port to 27018
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodb_data: