"""fix asset model

Revision ID: 3e0262dbea10
Revises: 6c205387f832
Create Date: 2025-12-15 20:26:13.358649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0262dbea10'
down_revision: Union[str, Sequence[str], None] = '6c205387f832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_uuid', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('assets_assetuuid_key'), 'assets', type_='unique')
    op.create_unique_constraint(None, 'assets', ['asset_uuid'])
    op.drop_column('assets', 'assetuuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('assetuuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assets', type_='unique')
    op.create_unique_constraint(op.f('assets_assetuuid_key'), 'assets', ['assetuuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'asset_uuid')
    # ### end Alembic commands ###
