"""Add initial commit

Revision ID: 93a8b5434978
Revises: 6e2dc435e31c
Create Date: 2025-12-15 11:38:24.565927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a8b5434978'
down_revision: Union[str, Sequence[str], None] = '6e2dc435e31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('new_dummy_column', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'new_dummy_column')
    # ### end Alembic commands ###
