"""add default to updated_at

Revision ID: aa7004120837
Revises: 93a8b5434978
Create Date: 2025-12-15 19:43:54.624577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7004120837'
down_revision: Union[str, Sequence[str], None] = '93a8b5434978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'new_dummy_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('new_dummy_column', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
